config/routes.rb
Rails.application.routes.draw do

  get 'teacher/view'
  # Dashboard -----------------------------------------------

  get 'teachers/list_teac'
  resources :students
  root 'static_pages#index'

  get 'signup', to: 'admins#new', as: 'signup'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  get 'success', to: 'select#success'

  get 'admin/login', to: 'sessions#new'
  post 'admin/login', to: 'sessions#create'

  get 'login', to: 'sessions#new_stud'
  post 'login', to: 'sessions#studcreate'

  get 'teacher/list', to: 'teacher#view'

  get 'help', to: 'static_pages#help'

  get 'list/students/view/send/login', to: 'admins#send_login_single'
  get 'list/students/view/send/punish', to: 'admins#punishmail_single'

  get 'process', to: 'admins#processor'

  get 'registrieren', to: 'select#list'

  get 'send/testmail', to: 'admins#testmail'
  get 'send/punishmail', to: 'admins#punishmail'
  get 'send/finallist', to: 'admins#finalmail'

  get 'confirm/selection', to: 'select#confirm'

  get 'force', to: 'sessions#force'
  get 'return', to: 'sessions#back'
  get 'choose', to: 'select#add'
  get 'remove', to: 'select#remove'
  get 'confirm/selection', to: 'select#confirm'

  get 'list/presentations', to: 'admins#list_pres'
  get 'list/teachers', to: 'admins#list_teac'
  get 'list/students', to: 'admins#list_stud'
  get 'list/teachers/all', to: 'admins#list_teac_all'

  get 'list/teachers/view', to: 'admins#view_teac'
  get 'list/students/view', to: 'admins#view_stud'

  post 'admin/new', to: 'admins#create'
  post 'teacher/new', to: 'admins#new_teac'
  post 'student/new', to: 'admins#new_stud'
  post 'presentation/new', to: 'admins#new_pres'

  get 'update/teacher', to: 'admins#edit_teac'
  get 'update/presentation', to: 'admins#edit_pres'
  get 'update/student', to: 'admins#edit_stud'
  post 'presentation/update', to: 'admins#update_presentation'
  post 'student/update', to: 'admins#update_student'

  get 'list/presentations/view', to: 'admins#view_pres'

  get 'send/loginmail', to: 'admins#send_login'

  get 'registration/send', to: 'select#sending'

  post 'admin/update', to: 'admins#update_admin'
  patch 'teacher/update', to: 'admins#update_teacher'
  post 'teacher/update', to: 'admins#update_teacher'


  get 'dashboard', to: 'admins#dashboard'

  get 'settings', to: 'admins#settings'
  get 'settings/activate', to: 'admins#act'
  get 'settings/deactivate', to: 'admins#deact'
  post 'settings/update', to: 'admins#update_set'

  get 'mailer', to: 'admins#mailer'

  get 'upload/teachers', to: 'admins#upload_teac'
  post 'upload/teachers', to: 'admins#import_teachers'

  get 'upload/error', to: 'admins#error_page_upload'

  get 'upload/students', to: 'admins#upload_stud'
  post 'upload/students', to: 'admins#import_students'

  get 'upload/presentations', to: 'admins#upload_pres'
  post 'upload/presentations', to: 'admins#import_presentations'

  get 'upload/settings', to: 'admins#prefs'
  post 'upload/settings', to: 'admins#prefs_upd'

  get 'upload/help', to: 'admins#upload_help'
  get 'settings/downloadsqlite', to: 'admins#download'

  get 'reset', to: 'admins#reset'
  get 'confirm', to: 'admins#clear'

  get 'delete/teacher', to: 'admins#del_teac'
  get 'delete/teacher/confirm', to: 'admins#del_teac_conf'

  get 'delete/presentation', to: 'admins#del_pres'
  get 'delete/presentation/confirm', to: 'admins#del_pres_conf'

  get 'delete/student', to: 'admins#del_stud'
  get 'delete/student/confirm', to: 'admins#del_stud_conf'
  resources :admins
  resources :students
  resources :presentations
  resources :sessions, only: [:new, :create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/admins/_modset.html.erb
<div class="modal fade" id="editSettingsModal" tabindex="-1" role="dialog" aria-labelledby="newAdminLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="newTeacherModalLabel">Servereinstellungen</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <%= form_tag settings_update_path do %>
      <div class="modal-body">
        <div class="form-new">
          Verlangte Anmeldungen
          <div class="input-group mb-3">
            <%= number_field_tag 'req', Pref.first.req, class: "form-control", min: 1, max: 10, step: 1 %>
            <div class="input-group-append">
              <span class="input-group-text">Anmeldungen</span>
            </div>
          </div>
          Verlangte Zeit zwischen Präsentationen
          <div class="input-group mb-3">
          <%= number_field_tag 'time', Pref.first.time.to_i / 60, class: "form-control", min: 1, max: 60, step: 1 %>
          <div class="input-group-append">
            <span class="input-group-text">Minuten</span>
          </div>
        </div>
          Anzahl freie Plätze pro Präsentation
          <div class="input-group mb-3">
          <%= number_field_tag 'free', Pref.first.free, class: "form-control", min: 1, max: 10, step: 1 %>
          <div class="input-group-append">
            <span class="input-group-text">Plätze</span>
          </div>
        </div>
          Datum
          <%= date_field_tag 'pres_date', Pref.first.pres_date, class: "form-control mb-3" %>
          Typ der Präsentationen
          <%= select_tag 'pres_type',  raw("<option>Gymnasium</option><option>FMS</option>"), class: "form-control" %>

        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Abbrechen</button>
        <%= submit_tag 'Speichern', class: "btn btn-primary btn-block" %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admins/_prmodal.html.erb
<div class="modal fade" id="newPresentationModal" tabindex="-1" role="dialog" aria-labelledby="newAdminLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="newTeacherModalLabel">Neue Präsentation</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <%= form_for(@presentation, url: presentation_new_path) do |f| %>
      <div class="modal-body">
        <div class="form-new">

          <%= f.label :vorname, 'Vorname', class: "sr-only" %>
          <%= f.text_field :vorname, class: "form-control", placeholder: "Vorname", id: "top", required: true %>

          <%= f.label :name, 'Name', class: "sr-only" %>
          <%= f.text_field :name, class: "form-control", placeholder: "Name", id: "mid", required: true %>

          <%= f.label :klasse, 'Klasse', class: "sr-only" %>
          <%= f.text_field :klasse, class: "form-control", placeholder: "Klasse", id: "mid", required: true %>

          <%= f.label :titel, 'Titel', class: "sr-only" %>
          <%= f.text_field :titel, class: "form-control", placeholder: "Titel", id: "mid", required: true %>

          <%= f.label :fach, 'Fach', class: "sr-only" %>
          <%= f.text_field :fach, class: "form-control", placeholder: "Fach", id: "mid", required: true %>

          <%= f.label :betreuer, 'Betreuer', class: "sr-only" %>
          <%= f.text_field :betreuer, class: "form-control", placeholder: "Betreuer", id: "mid", required: true %>

          <%= f.label :zimmer, 'Zimmer', class: "sr-only" %>
          <%= f.text_field :zimmer, class: "form-control", placeholder: "Zimmer", id: "mid", required: true %>

          <%= f.label :von, 'Von', class: "sr-only" %>
          <%= f.text_field :von, class: "form-control", placeholder: "Von", id: "mid", required: true %>

          <%= f.label :bis, 'Bis', class: "sr-only" %>
          <%= f.text_field :bis, class: "form-control", placeholder: "Bis", id: "btm", required: true %>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Abbrechen</button>
        <%= f.submit 'Speichern', class: "btn btn-primary btn-block" %>
      </div>
      <% end %>
    </div>
  </div>
</div>

<div class="modal fade" id="errorModal" tabindex="-1" role="dialog" aria-labelledby="newAdminLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="newTeacherModalLabel">Error</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        Den Lehrer gibt es nicht!
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">OK</button>
      </div>
    </div>
  </div>
</div>

app/views/admins/_table_pres.html.erb
<table class="table table-hover sorttable">
  <thead>
    <tr class="srt">
      <th>Vorname</th>
      <th>Nachname</th>
      <th>Klasse</th>
      <th>Titel</th>
      <th>Fach</th>
      <th>Betreuer</th>
      <th>Zimmer</th>
      <th>Von</th>
      <th>Bis</th>
      <th>Frei</th>
      <th>Aktionen</th>
    </tr>
  </thead>
  <%= yield %>
  

app/views/admins/_teac_form.html.erb
<div class="form-new">
  <%= form_tag teacher_update_path do %>
    <%= hidden_field_tag :id, @teacher.id %>
    <%= text_field_tag :vorname, @teacher.vorname, class: "form-control", placeholder:"Vorname", id: "top" %>
    <%= text_field_tag :name, @teacher.name, class: "form-control", placeholder:"Name", id: "mid" %>
    <%= text_field_tag :mail, @teacher.mail, class: "form-control", placeholder:"Mail", id: "mid" %>
    <%= text_field_tag :number, @teacher.number, class: "form-control", placeholder:"Nummer", id: "btm" %>
    <%= submit_tag :Speichern, class:"btn btn-lg btn-block btn-primary mt-3" %>
  <% end %>
</div>

app/views/admins/dashboard.html.erb
<div class="card mb-3">
  <div class="card-header">
    System Status
  </div>
  <div class="card-body">
    <div class="row">
      <div class="col-sm">
        <% if Pref.first.login %>
          Anmeldungen: <span class="text-success font-weight-bold">Aktiviert</span><br>
        <% else %>
          Anmeldungen: <span class="text-danger font-weight-bold">Deaktiviert</span><br>
        <% end %>
        <% if @studrec == 0 %>
        Mailer Status: <span class="text-danger font-weight-bold">Mails wurden noch nicht verschickt</span>
        <% elsif @studrec == 1 %>
        Mailer Status: <span class="text-success font-weight-bold">Online</span>
        <% else %>
        Mailer Status: <span class="text-danger font-weight-bold">Mails wurden noch nicht an allen Schülern verschickt</span>
        <% end %>
      </div>
      <div class="col-sm">
        <table class="table table-sm">
          <tbody>
            <tr>
              <td>Anzahl Schüler</td>
              <td><%= Student.all.count %></td>
            </tr>
            <tr>
              <td>Anzahl Präsentationen</td>
              <td><%= Presentation.all.count %></td>
            </tr>
            <tr>
              <td>Anzahl Anmeldungen</td>
              <td><%= Student.where(register: true).count %></td>
            </tr>
          </tbody>
        </table>
        Fortschritt:
        <div class="progress">
          <div class="progress-bar bg-info" role="progressbar" style="width: <%= (Student.where(register: true).count.to_f / Student.all.count.to_f) * 100 %>%" aria-valuenow="10" aria-valuemin="0" aria-valuemax="100"><% unless Student.where(register: true).count == 0 %><%= ((Student.where(register: true).count.to_f / Student.all.count.to_f) * 100).round(1) %>%<% end %></div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-sm">
    <div class="card mb-3">
      <div class="card-header">
        Datenbank Verwaltung
      </div>
      <div class="card-body">

        <% if Presentation.first == nil || Teacher.first == nil || Student.first == nil %>
          <p class="card-text">Die Datenbank ist noch nicht vollständig ausgefüllt.</p>
          <%= link_to "Jetzt Ausfüllen...", upload_teachers_path, class: "btn btn-primary"%>
        <% else %>
          <h5 class="card-title">Verfügbare Tabellen:</h5>
          <div class="btn-group" role="group" aria-label="Basic example">
            <%= link_to 'Lehrer', list_teachers_path, class:"btn btn-secondary" %>
            <%= link_to 'Präsentationen', list_presentations_path, class:"btn btn-secondary" %>
            <%= link_to 'Schüler', list_students_path, class:"btn btn-secondary" %>
          </div>
        <% end %>

      </div>
    </div>
  </div>
  <div class="col-sm mb-3">
    <div class="card">
      <div class="card-header">
        Mailer
      </div>
      <div class="card-body">
        <h5 class="card-title"></h5>
        <%= link_to 'Mailerverwaltung öffnen', mailer_path, class: 'btn-primary btn' %>
      </div>
    </div>
  </div>
  <div class="col-sm mb-3">
    <div class="card">
      <div class="card-header">
        Servereinstellungen
      </div>
      <div class="card-body">
        <h5 class="card-title"></h5>
        Current user type:
        <% if logged_ad? %>
        Admin, <%= @current_admin.handle %>
        <% elsif logged_stud? %>
        Student.
        <% end %>
        <hr>
        <%= link_to 'Einstellungen', settings_path, class: 'btn-primary btn' %>
        <hr>
        <%= link_to 'Admins verwalten', admins_path, class: 'btn btn-primary' %>
        <%= link_to 'Reset', reset_path, class: 'btn-danger btn' %>
      </div>
    </div>
  </div>
</div>
<br>
<br>

app/views/admins/del_pres.html.erb
<h4 class="mb-3">Möchten Sie diese Präsentation wirklich entfernen?</h4>
<table class="table table-hover sorttable table-sm">
  <thead>
    <tr class="srt">
      <th>Vorname</th>
      <th>Nachname</th>
      <th>Klasse</th>
      <th>Titel</th>
      <th>Fach</th>
      <th>Betreuer</th>
      <th>Zimmer</th>
      <th>Von</th>
      <th>Bis</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= @presentation.vorname %></td>
      <td><%= @presentation.name %></td>
      <td><%= @presentation.klasse %></td>
      <td><%= @presentation.titel %></td>
      <td><%= @presentation.fach %></td>
      <td><%= link_to @presentation.betreuer, list_teachers_view_path(:number => @presentation.betreuer) %></td>
      <td><%= @presentation.zimmer %></td>
      <td><%= Time.at(@presentation.von.to_f).utc.strftime("%H:%M") %></td>
      <td><%= Time.at(@presentation.bis.to_f).utc.strftime("%H:%M") %></td>
    </tr>
  </tbody>
</table>

<%= link_to "Löschen", delete_presentation_confirm_path(:id => @presentation.id), class: "btn btn-danger" %>

app/views/admins/del_teac.html.erb
<% if Presentation.where(betreuer: @teac.number).count > 0 %>
<div class="card mb-3">
  <div class="card-header">
    Warnung
  </div>
  <div class="card-body">
    <h5 class="card-title">Wenn Sie <%= @teac.vorname %> <%= @teac.name %> entfernen, werden folgende Präsentationen auch entfernt:</h5>
    <table class="table table-hover sorttable table-sm">
      <thead>
        <tr class="srt">
          <th>Vorname</th>
          <th>Nachname</th>
          <th>Klasse</th>
          <th>Titel</th>
          <th>Fach</th>
          <th>Betreuer</th>
          <th>Zimmer</th>
          <th>Von</th>
          <th>Bis</th>
          <th>Frei</th>
        </tr>
      </thead>
      <tbody>
        <% @presentations.each do |pres| %>
          <tr>
            <td><%= pres.vorname %></td>
            <td><%= pres.name %></td>
            <td><%= pres.klasse %></td>
            <td><%= pres.titel %></td>
            <td><%= pres.fach %></td>
            <td><span rel="tooltip" data-toggle="tooltip" style="cursor: pointer;" title="<%= Teacher.find_by(number: pres.betreuer).vorname %> <%= Teacher.find_by(number: pres.betreuer).name %>"><%= pres.betreuer %></span></td>
            <td><%= pres.zimmer %></td>
            <td><%= Time.at(pres.von.to_f).utc.strftime("%H:%M") %></td>
            <td><%= Time.at(pres.bis.to_f).utc.strftime("%H:%M") %></td>
            <td><%= Pref.first.free - pres.visit.count %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= link_to 'Trotzdem entfernen', delete_teacher_confirm_path(:id => @teac.id), class: "btn btn-danger" %>
  </div>
</div>
<% else %>
<h4>Möchten Sie <%= @teac.vorname %> <%= @teac.name %> wirklich entfernen?</h4> <br>
<%= link_to 'Entfernen', delete_teacher_confirm_path(:id => @teac.id), class: "btn btn-danger" %>
<% end %>

app/views/admins/edit_stud.html.erb
<div class="card p-3 mb-5 bg-white rounded" style="max-width: 400px; margin: auto">
  <div class="card-body">
    <h4>Student bearbeiten</h4>
    <div class="form-new wide">
      <%= form_tag student_update_path do %>
        <%= hidden_field_tag :id, @student.id %>
        <%= text_field_tag :vorname, @student.vorname, class: "form-control", placeholder:"Vorname", id: "top" %>
        <%= text_field_tag :name, @student.name, class: "form-control", placeholder:"Name", id: "mid" %>
        <%= text_field_tag :klasse, @student.klasse, class: "form-control", placeholder:"Klasse", id: "mid" %>
        <%= text_field_tag :mail, @student.mail, class: "form-control", placeholder:"Titel", id: "mid" %>
        <%= text_field_tag :number, @student.number, class: "form-control", placeholder:"Fach", id: "btm" %>

        <%= submit_tag :Speichern, class:"btn btn-lg btn-block btn-primary mt-3" %>
      <% end %>
    </div>
  </div>
</div>

app/views/admins/edit_teac.html.erb
<div class="card p-3 mb-5 bg-white rounded" style="max-width: 400px; margin: auto">
  <div class="card-body">
    <h4>Lehrer bearbeiten</h4>
    <%= render 'teac_form' %>
  </div>
</div>

app/views/admins/list_stud.html.erb
<%= render 'navlist' %>
<div class="float-right">
  <button type="button" name="button" class="btn btn-primary mb-3" data-toggle="modal" data-target="#newStudentModal">Hinzufügen</button>
</div>


<table class="table table-hover sorttable">
  <thead>
    <tr>
      <th>Name</th>
      <th>Klasse</th>
      <th>Mail</th>
      <th>Nummer</th>
      <th>Passwort</th>
      <th>Status</th>
      <th>Aktionen</th>
    </tr>
  </thead>
  <tbody>
    <% @students.each do |stud| %>
      <% if !stud.rec && Pref.first.log_data %>
        <tr class="table-info">
      <% elsif !stud.register && Pref.first.log_data %>
        <tr class="table-warning">
      <% else %>
        <tr>
      <% end %>
        <td><%= stud.vorname %> <%= stud.name %></td>
        <td><%= stud.klasse %></td>
        <td><%= stud.mail %></td>
        <td><%= stud.number %></td>
        <td><%= stud.code %></td>
        <% if stud.register %>
          <td><%= show_svg('check.svg') %></td>
        <% else %>
          <td><%= show_svg('close.svg') %></td>
        <% end %>
        <td>
          <div class="dropdown">
            <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Aktionen
            </button>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
              <%= link_to "Infos", list_students_view_path(:id => stud.id), class: "btn btn-secondary dropdown-item" %>
              <%= link_to "Bearbeiten", update_student_path(:id => stud.id), class: "btn btn-secondary dropdown-item" %>
              <% unless stud.register %>
                <%= link_to "Force", force_path(:id => stud.id), class: "btn btn-primary dropdown-item" %>
              <% end %>
              <% unless stud.register == true %>
                <div class="dropdown-divider"></div>
                <%= link_to "Entfernen", delete_student_path(:id => stud.id), class: "btn btn-warning dropdown-item" %>
              <% end %>
            </div>
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= render 'stmodal' %>

app/views/admins/new.html.erb
<h1>New Admin</h1>

<%= render 'form', admin: @admin %>

<%= link_to 'Back', admins_path %>

app/views/admins/settings.html.erb
<div class="row">
  <div class="col-sm">
    <div class="card mb-3">
      <div class="card-header success">
        Einstellungen
      </div>
      <div class="card-body">
        <% if Pref.first.login %>
          <h5 class="card-title">Status: <span class="text-success font-weight-bold">Online</span></h5>
          <p class="card-text">Anmeldungen sind aktiviert</p>
          <%= link_to "Jetzt Deaktivieren", settings_deactivate_path, class: "btn btn-danger" %>
        <% else %>
          <h5 class="card-title">Status: <span class="text-danger font-weight-bold">Deaktiviert</span></h5>
          <p class="card-text">Anmeldungen sind nicht aktiviert</p>
          <%= link_to "Jetzt Aktivieren", settings_activate_path, class: "btn btn-success" %>
        <% end %>
        <hr>
        <h5 class="card-title">SQLite Datenbank herunterladen</h5>
        <%= link_to "Jetzt herunterladen", settings_downloadsqlite_path, class: 'btn btn-primary' %>
      </div>
    </div>
  </div>
  <div class="col-sm">
    <div class="card">
      <div class="card-header success">
        Anmeldeeinstellungen
      </div>
      <div class="card-body">
        <table class="table table-sm">
            <caption>Diese Werte können nicht bearbeitet werden, nachdem die Mails mit den Anmeldedaten verschickt worden sind.</caption>
          <tbody>
            <tr>
              <td>Verlangte Anmeldungen:</td>
              <td><%= Pref.first.req %></td>
            </tr>
            <tr>
              <td>Zeit zwischen Präsentationen:</td>
              <td><%= Pref.first.time / 60 %> Minuten</td>
            </tr>
            <tr>
              <td>Freie Plätze pro Präsentation:</td>
              <td><%= Pref.first.free %></td>
            </tr>
            <tr>
              <td>Datum</td>
              <td><%= Date.parse(Pref.first.pres_date).strftime("%d/%m/%Y") %></td>
            </tr>
            <tr>
              <td>Präsentationen Typ</td>
              <% if Pref.first.pres_type == 0 %>
                <% type = "Gymnasium" %>
              <% elsif Pref.first.pres_type == 1 %>
                <% type = "FMS" %>
              <% end %>
              <td><%= type %></td>
            </tr>
          </tbody>
        </table>
        <% if Student.all.where(rec: true).count == 0 %>
          <button type="button" name="button" class="btn btn-primary btn-block" data-toggle="modal" data-target="#editSettingsModal">Bearbeiten</button>
        <% end %>
      </div>
    </div>
  </div>
</div>

<%= render 'modset' %>

app/views/admins/spinner.html.erb
<div class="spinner-border" role="status">
  <span class="sr-only">Loading...</span>
</div>

app/views/admins/upload_teac.html.erb
<div class="card shadow p-3 mb-5 bg-white rounded" style="max-width: 400px; margin: auto;">
  <div class="card-body">
    <h5 class="card-title">Lehrer hinzufügen</h5>
    <%= form_tag upload_teachers_path, multipart: true do %>
      <%= file_field_tag :file, class: "form-control-file my-3" %>
      <%= submit_tag "Import CSV", data: { disable_with: "Wird hochgeladen..." }, class: "special-upload-button" %>
      <%= link_to 'Hilfe', upload_help_path, class: "card-link" %>
    <% end  %>
  </div>
</div>