config/routes.rb
Rails.application.routes.draw do

  get 'teacher/view'
  # Dashboard -----------------------------------------------

  get 'teachers/list_teac'
  resources :students
  root 'static_pages#index'

  get 'signup', to: 'admins#new', as: 'signup'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  get 'success', to: 'select#success'

  get 'admin/login', to: 'sessions#new'
  post 'admin/login', to: 'sessions#create'

  get 'login', to: 'sessions#new_stud'
  post 'login', to: 'sessions#studcreate'

  get 'teacher/list', to: 'teacher#view'

  get 'help', to: 'static_pages#help'

  get 'list/students/view/send/login', to: 'admins#send_login_single'
  get 'list/students/view/send/punish', to: 'admins#punishmail_single'

  get 'process', to: 'admins#processor'

  get 'registrieren', to: 'select#list'

  get 'send/testmail', to: 'admins#testmail'
  get 'send/punishmail', to: 'admins#punishmail'
  get 'send/finallist', to: 'admins#finalmail'

  get 'confirm/selection', to: 'select#confirm'

  get 'force', to: 'sessions#force'
  get 'return', to: 'sessions#back'
  get 'choose', to: 'select#add'
  get 'remove', to: 'select#remove'
  get 'confirm/selection', to: 'select#confirm'

  get 'list/presentations', to: 'admins#list_pres'
  get 'list/teachers', to: 'admins#list_teac'
  get 'list/students', to: 'admins#list_stud'
  get 'list/teachers/all', to: 'admins#list_teac_all'

  get 'list/teachers/view', to: 'admins#view_teac'
  get 'list/students/view', to: 'admins#view_stud'

  post 'admin/new', to: 'admins#create'
  post 'teacher/new', to: 'admins#new_teac'
  post 'student/new', to: 'admins#new_stud'
  post 'presentation/new', to: 'admins#new_pres'

  get 'update/teacher', to: 'admins#edit_teac'
  get 'update/presentation', to: 'admins#edit_pres'
  get 'update/student', to: 'admins#edit_stud'
  post 'presentation/update', to: 'admins#update_presentation'
  post 'student/update', to: 'admins#update_student'

  get 'list/presentations/view', to: 'admins#view_pres'

  get 'send/loginmail', to: 'admins#send_login'

  get 'registration/send', to: 'select#sending'

  post 'admin/update', to: 'admins#update_admin'
  patch 'teacher/update', to: 'admins#update_teacher'
  post 'teacher/update', to: 'admins#update_teacher'


  get 'dashboard', to: 'admins#dashboard'

  get 'settings', to: 'admins#settings'
  get 'settings/activate', to: 'admins#act'
  get 'settings/deactivate', to: 'admins#deact'
  post 'settings/update', to: 'admins#update_set'

  get 'mailer', to: 'admins#mailer'

  get 'upload/teachers', to: 'admins#upload_teac'
  post 'upload/teachers', to: 'admins#import_teachers'

  get 'upload/error', to: 'admins#error_page_upload'

  get 'upload/students', to: 'admins#upload_stud'
  post 'upload/students', to: 'admins#import_students'

  get 'upload/presentations', to: 'admins#upload_pres'
  post 'upload/presentations', to: 'admins#import_presentations'

  get 'upload/settings', to: 'admins#prefs'
  post 'upload/settings', to: 'admins#prefs_upd'

  get 'upload/help', to: 'admins#upload_help'
  get 'settings/downloadsqlite', to: 'admins#download'

  get 'reset', to: 'admins#reset'
  get 'confirm', to: 'admins#clear'

  get 'delete/teacher', to: 'admins#del_teac'
  get 'delete/teacher/confirm', to: 'admins#del_teac_conf'

  get 'delete/presentation', to: 'admins#del_pres'
  get 'delete/presentation/confirm', to: 'admins#del_pres_conf'

  get 'delete/student', to: 'admins#del_stud'
  get 'delete/student/confirm', to: 'admins#del_stud_conf'
  resources :admins
  resources :students
  resources :presentations
  resources :sessions, only: [:new, :create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/select_controller.rb
class SelectController < ApplicationController
    def list
        if current_student.select.count == Pref.first.req
            redirect_to confirm_selection_path
        end
        @presentations = []
        Presentation.all.each do |p|
            if Pref.first.free - p.visit.count > 0 || current_student.select.include?(p.id)
                @presentations << p
            else
            end
        end
    end

    def success

    end

    def add
        pres = Presentation.find_by_id(params_allow)
        pres.save
        current_student.select << pres.id
        current_student.save
        redirect_to registrieren_path
    end

    def remove
        pres = Presentation.find_by_id(params_allow)
        pres.save
        current_student.select.delete(pres.id)
        current_student.save
        redirect_to registrieren_path
    end

    def confirm
        @presentations = []
        current_student.select.each do |p|
            pres = Presentation.find_by_id(p)
            @presentations << pres
        end
    end

    def sending     
        count = 0        
        current_student.select.each do |s|
            pres = Presentation.find_by_id(s)
            if Pref.first.free - pres.visit.count <= 0
                current_student.select.delete(s)
                current_student.save
                count += 1
            end
        end
        if count == 0
            current_student.select.each do |s|
                p = Presentation.find_by_id(s)
                p.visit << current_student
                p.save
            end
            current_student.register = true
            current_student.save
            StudentMailer.final_mail(current_student).deliver_now
            session[:student_id] = nil
            if logged_ad?
              redirect_to list_students_path
            else
              redirect_to success_url, notice: "Session beendet"
            end
        else
            redirect_to registrieren_path
            if count == 1
                flash[:error] = "#{count} Präsentation sind nicht mehr verfügbar, sie wurden entfernt. Bitte versuchen Sie es nocheinmal."
            else
                flash[:error] = "#{count} Präsentationen sind nicht mehr verfügbar, sie wurden entfernt. Bitte versuchen Sie es nocheinmal."
            end     
        end
    end
    private

    def params_allow
        params.require(:id)
    end
end

app/helpers/select_helper.rb
module SelectHelper
end

app/views/select/_warn.html.erb
<div class="modal fade" id="warnStudentModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="warnStudentLabel">Warnung</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        Nachdem Sie Ihre Anmeldung abschicken, können Sie Ihre Wahl nich mehr ändern. Wirklich absenden?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Zurück</button>
        <%= link_to 'Absenden', registration_send_path, class: "btn btn-primary" %>
      </div>
    </div>
  </div>
</div>

app/views/select/confirm.html.erb
<div class="card">
    <div class="card-header">
        Ausgewählte Präsentationen
    </div>
    <div class="card-body">
        <h5 class="card-title">Sie haben folgende Präsentationen ausgewählt:</h5>
        <table class="table table-hover sorttable">
            <thead>
                <tr class="srt">
                    <th>Vorname</th>
                    <th>Nachname</th>
                    <th>Klasse</th>
                    <th>Titel</th>
                    <th>Fach</th>
                    <th>Betreuer</th>
                    <th>Zimmer</th>
                    <th>Von</th>
                    <th>Bis</th>
                    <th>Frei</th>
                    <th>Abwählen</th>
                </tr>
            </thead>
            <tbody>
                <% @presentations.each do |pres| %>
                    <tr>
                        <td><%= pres.vorname %></td>
                        <td><%= pres.name %></td>
                        <td><%= pres.klasse %></td>
                        <td><%= pres.titel %></td>
                        <td><%= pres.fach %></td>
                        <% btr = Teacher.find_by_number(pres.betreuer) %>
                        <td><%= btr.vorname %> <%= btr.name %></td>
                        <td><%= pres.zimmer %></td>
                        <td><%= Time.at(pres.von.to_f).utc.strftime("%H:%M") %></td>
                        <td><%= Time.at(pres.bis.to_f).utc.strftime("%H:%M") %></td>
                        <td><%= Pref.first.free - pres.visit.count %></td>
                        <td><%= link_to 'Entfernen', remove_path(:id => pres.id), class: "btn btn-primary btn-block" %>
                    </tr>
                <% end %>
            </tbody>
        </table>  
        <button type="button" name="button" class="btn btn-success btn-block" data-toggle="modal" data-target="#warnStudentModal">Anmeldung abschliessen</button>
    </div>
</div>

<%= render 'warn' %>

app/views/select/list.html.erb
<table class="table table-hover sorttable">
  <thead>
    <tr class="srt">
      <th>Vorname</th>
      <th>Nachname</th>
      <th>Klasse</th>
      <th>Titel</th>
      <th>Fach</th>
      <th>Betreuer</th>
      <th>Zimmer</th>
      <th>Von</th>
      <th>Bis</th>
      <th>Frei</th>
      <th>Wählen</th>
    </tr>
  </thead>
  <tbody>
    <% @presentations.each do |pres| %>
      <% if current_student.select.include?(pres.id) %>
        <tr class="table-info">
      <% else %>
        <tr>
      <% end %>
          <td><%= pres.vorname %></td>
          <td><%= pres.name %></td>
          <td><%= pres.klasse %></td>
          <td><%= pres.titel %></td>
          <td><%= pres.fach %></td>
          <% btr = Teacher.find_by_number(pres.betreuer) %>
          <td><%= btr.vorname %> <%= btr.name %></td>
          <td><%= pres.zimmer %></td>
          <td><%= Time.at(pres.von.to_f).utc.strftime("%H:%M") %></td>
          <td><%= Time.at(pres.bis.to_f).utc.strftime("%H:%M") %></td>
          <td><%= Pref.first.free - pres.visit.count %></td>
          <% compat = [] %>
          <% current_student.select.each do |s| %>
            <% p = Presentation.find_by_id(s) %>
            <% if p.von == pres.von || ( pres.von.to_i - p.bis.to_i < Pref.first.time && pres.von.to_i - p.bis.to_i > 0) || (p.von.to_i - pres.bis.to_i < Pref.first.time && p.von.to_i - pres.bis.to_i > 0) %>
              <% compat << false %>
            <% else %>
              <% compat << true %>
            <% end %>
          <% end %>
          <% if compat.all? %>
            <td>
              <% if current_student.select.include?(pres.id) %>
              <% elsif !current_student.select.include?(pres.id) %>
                <%= link_to 'Wählen', choose_path(:id => pres.id), class: "btn btn-primary btn-block" %>
              <% end %>
            </td>
          <% elsif current_student.select.include?(pres.id) %>
            <td>
              <%= link_to 'Entfernen', remove_path(:id => pres.id), class: "btn btn-primary btn-block" %>
            </td>
          <% else %>
            <td></td>
          <% end %>
        </tr>
    <% end %>
  </tbody>
</table>

<!--
<div id="fixedinfo" class="shadow bg-warning">
  <% if Pref.first.req.to_i - current_student.select.count > 1 %>
    Sie müssen noch <%= Pref.first.req.to_i - current_student.select.count %> Präsentationen auswählen.
  <% elsif Pref.first.req.to_i - current_student.select.count == 1 %>
    Sie müssen noch <%= Pref.first.req.to_i - current_student.select.count %> Präsentation auswählen.
  <% end %>
</div>
-->



<div class="card text-white bg-info shadow" id="fixedcard" style="max-width: 18rem;">
  <div class="card-header">Information</div>
  <div class="card-body">
    <% if Pref.first.req.to_i - current_student.select.count > 1 %>
      Sie müssen noch <%= Pref.first.req.to_i - current_student.select.count %> Präsentationen auswählen.
    <% elsif Pref.first.req.to_i - current_student.select.count == 1 %>
      Sie müssen noch <%= Pref.first.req.to_i - current_student.select.count %> Präsentation auswählen.
    <% end %>
  </div>
</div>
<br /><br /><br /><br /><br /><br />

app/views/select/success.html.erb
<div class="card text-center">
  <div class="card-header">
    BKS-Tool
  </div>
  <div class="card-body">
    <h5 class="card-title">Vielen Dank</h5>
    <p class="card-text">Sie haben sich erfolgreich für die Präsentationen angemolden. Schauen Sie in ihrem Inbox für eine Bestätigung.</p>
  </div>
  <div class="card-footer text-muted">
    Erstellt von Edward Lancaster MA18 - v.20.11 <br />
  </div>
</div>