config/routes.rb
Rails.application.routes.draw do

  get 'teacher/view'
  # Dashboard -----------------------------------------------

  get 'teachers/list_teac'
  resources :students
  root 'static_pages#index'

  get 'signup', to: 'admins#new', as: 'signup'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  get 'success', to: 'select#success'

  get 'admin/login', to: 'sessions#new'
  post 'admin/login', to: 'sessions#create'

  get 'login', to: 'sessions#new_stud'
  post 'login', to: 'sessions#studcreate'

  get 'teacher/list', to: 'teacher#view'

  get 'help', to: 'static_pages#help'

  get 'list/students/view/send/login', to: 'admins#send_login_single'
  get 'list/students/view/send/punish', to: 'admins#punishmail_single'

  get 'process', to: 'admins#processor'

  get 'registrieren', to: 'select#list'

  get 'send/testmail', to: 'admins#testmail'
  get 'send/punishmail', to: 'admins#punishmail'
  get 'send/finallist', to: 'admins#finalmail'

  get 'confirm/selection', to: 'select#confirm'

  get 'force', to: 'sessions#force'
  get 'return', to: 'sessions#back'
  get 'choose', to: 'select#add'
  get 'remove', to: 'select#remove'
  get 'confirm/selection', to: 'select#confirm'

  get 'list/presentations', to: 'admins#list_pres'
  get 'list/teachers', to: 'admins#list_teac'
  get 'list/students', to: 'admins#list_stud'
  get 'list/teachers/all', to: 'admins#list_teac_all'

  get 'list/teachers/view', to: 'admins#view_teac'
  get 'list/students/view', to: 'admins#view_stud'

  post 'admin/new', to: 'admins#create'
  post 'teacher/new', to: 'admins#new_teac'
  post 'student/new', to: 'admins#new_stud'
  post 'presentation/new', to: 'admins#new_pres'

  get 'update/teacher', to: 'admins#edit_teac'
  get 'update/presentation', to: 'admins#edit_pres'
  get 'update/student', to: 'admins#edit_stud'
  post 'presentation/update', to: 'admins#update_presentation'
  post 'student/update', to: 'admins#update_student'

  get 'list/presentations/view', to: 'admins#view_pres'

  get 'send/loginmail', to: 'admins#send_login'

  get 'registration/send', to: 'select#sending'

  post 'admin/update', to: 'admins#update_admin'
  patch 'teacher/update', to: 'admins#update_teacher'
  post 'teacher/update', to: 'admins#update_teacher'


  get 'dashboard', to: 'admins#dashboard'

  get 'settings', to: 'admins#settings'
  get 'settings/activate', to: 'admins#act'
  get 'settings/deactivate', to: 'admins#deact'
  post 'settings/update', to: 'admins#update_set'

  get 'mailer', to: 'admins#mailer'

  get 'upload/teachers', to: 'admins#upload_teac'
  post 'upload/teachers', to: 'admins#import_teachers'

  get 'upload/error', to: 'admins#error_page_upload'

  get 'upload/students', to: 'admins#upload_stud'
  post 'upload/students', to: 'admins#import_students'

  get 'upload/presentations', to: 'admins#upload_pres'
  post 'upload/presentations', to: 'admins#import_presentations'

  get 'upload/settings', to: 'admins#prefs'
  post 'upload/settings', to: 'admins#prefs_upd'

  get 'upload/help', to: 'admins#upload_help'
  get 'settings/downloadsqlite', to: 'admins#download'

  get 'reset', to: 'admins#reset'
  get 'confirm', to: 'admins#clear'

  get 'delete/teacher', to: 'admins#del_teac'
  get 'delete/teacher/confirm', to: 'admins#del_teac_conf'

  get 'delete/presentation', to: 'admins#del_pres'
  get 'delete/presentation/confirm', to: 'admins#del_pres_conf'

  get 'delete/student', to: 'admins#del_stud'
  get 'delete/student/confirm', to: 'admins#del_stud_conf'
  resources :admins
  resources :students
  resources :presentations
  resources :sessions, only: [:new, :create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<footer class="footer mt-auto py-3">
  <div class="container">
    <span class="text-muted">Place sticky footer content here.</span>
  </div>
</footer>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
  <%= link_to 'BKS-Tool', root_path, class: 'navbar-brand' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarsExampleDefault">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item <%= 'active' if current_page?(root_path) %>">
        <%= link_to 'Home', root_path, class: "nav-link" %>
      </li>

      <% if logged_ad? && !logged_stud? %>
        <li class="nav-item <%= 'active' if current_page?(dashboard_path) %>">
          <%= link_to 'Dashboard', dashboard_path, class: 'nav-link' %>
        </li>

        <li class="nav-item">
          <%= link_to 'Abmelden', logout_path, class: "nav-link" %>
        </li>

      <% elsif logged_stud? && !logged_ad? %>
        <% unless current_student.select.count == Pref.first.req %>
          <li class="nav-item <%= 'active' if current_page?(registrieren_path) %>">
            <%= link_to 'Registration', registrieren_path, class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item <%= 'active' if current_page?(confirm_selection_path) %>">
            <%= link_to 'Bestätigung', confirm_selection_path, class: "nav-link" %>
          </li>
        <% end %>
        <li class="nav-item">
          <%= link_to 'Abmelden', logout_path, class: "nav-link" %>
        </li>
      <% elsif logged_stud? && logged_ad? %>
        <li class="nav-item">
          <%= link_to 'Zurück', return_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Abmelden', logout_path, class: "nav-link" %>
        </li>
      <% else %>
        <li class="nav-item <%= 'active' if current_page?(login_path) %>">
          <%= link_to 'Anmelden', login_path, class: "nav-link" %>
        </li>
        <li class="nav-item <%= 'active' if current_page?(help_path) %>">
          <%= link_to 'Hilfe', help_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
    <% if logged_ad? && logged_stud? %>
      <strong class="white-text">GOD MODE</strong>
    <% elsif logged_ad? && !logged_stud? %>
      <span class="white-text">Administrator <%= current_admin.handle %></span>
    <% elsif !logged_ad? && logged_stud? %>
      <span class="white-text"><%= current_student.vorname %> <%= current_student.name %>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <% if current_page?(root_path) %>
      <title>BKS Tool</title>
    <% elsif current_page?(login_path) %>
      <title>Anmelden - BKS Tool</title>
    <% elsif current_page?(dashboard_path) %>
      <title>Dashboard</title>
    <% elsif current_page?(list_teachers_path) || current_page?(list_presentations_path) || current_page?(list_students_path) || current_page?(list_teachers_all_path) %>
      <title>Datenbank</title>
    <% elsif current_page?(mailer_path) %>
      <title>Mailer</title>
    <% elsif current_page?(settings_path) %>
      <title>Einstellungen</title>
    <% elsif current_page?(admins_path) %>
      <title>Administratoren</title>
    <% elsif current_page?(reset_path) %>
      <title>Zurücksetzen</title>
    <% elsif current_page?(list_teachers_view_path) || current_page?(list_students_view_path) || current_page?(list_presentations_view_path) %>
      <title>Infos</title>
    <% end %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <% if current_page?(list_students_path) || current_page?(list_teachers_path) || current_page?(list_presentations_path) %>
      <%= render 'shared/js/sorttable' %>
      <script>
        $(document).on("page.change", sorttable.init)
      </script>
    <% else %>
    <% end %>
    <% flash.each do |key, value| %>
      <div class="<%= flash_class(key) %> alert-dismissible fade show" role="alert">
        <%= value %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
      </button>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>